name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Build with Maven and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: langBuddyBackend
          path: target/server*.jar
      - name: Push to Dockerhub
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: langbuddy/server
          tag_with_ref: true
          tag_with_sha: true
      - name: Deploy to Heroku (master)
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_PROD}}
          heroku_app_name: "langbuddy-prod"
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  positiveifttt:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: screendriver/ifttt-action@v1
        with:
          event: build_positive
          key: iAXu6S-kPL_-ntb878TOGmkW7uWJxscnG16w_UFl4UA

  negativeifttt:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - uses: screendriver/ifttt-action@v1
        with:
          status: failure
          event: build_failed
          key: iAXu6S-kPL_-ntb878TOGmkW7uWJxscnG16w_UFl4UA
        if: env.WORKFLOW_CONCLUSION == 'failure'

