name: Java CI

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven and analyze
        run: mvn clean verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: sonarsource/sonarcloud-github-action@master
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: langBuddyBackend
          path: target/server*.jar
      - name: Deploy to Heroku (staging)
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_STAGING}}
          heroku_app_name: "langbuddy-staging"
          heroku_email: ${{secrets.HEROKU_EMAIL}}